### ISSUE TITLE
Forumview

### ISSUE THREAD

**Issue by hanakin** [phpbb/chameleon#23]
We need a page to display the topics in a list.

Required components:
- [x] toolbar
- [x] topic
- [x] alert
- [x] jumpto

**Comment by poVoq** [comment]
Flarum might be a nice example for a topics list with tags/categories in the side bar:
https://discuss.flarum.org/

**Comment by hanakin** [comment]
Thanks but we already have a component for the topic list https://codepen.io/hanakin/pen/dNVWmm
