### ISSUE TITLE
Emoji/Smiles Picker Component

### ISSUE THREAD

**Issue by hanakin** [phpbb/chameleon#31]
We need a component for an emoji picker with integrated custom emojis (smileys) and a featured emojis section.

https://codepen.io/hanakin/pen/ErBPLL?editors=1100

**Comment by marc1706** [comment]
I saw the "Codepen Created" label and was hoping to see link to it here. Shouldn't you also post the link to the codepen when adding that label? Thanks ;)

**Comment by hanakin** [comment]
yeah still working out how It would flow was not sure if It made sense to have it in the issue or not. Or if it was just something that would be a step of the pr.
