### ISSUE TITLE
Fixed or fluid

### ISSUE THREAD

**Issue by veryard** [phpbb/chameleon#38]
Just had a look at the design, look nice, just question is there any reason that the header contents are fluid where as the forum list is in a fixed container?

![image](https://user-images.githubusercontent.com/3941758/54931153-75dfec80-4f53-11e9-9de7-d5693e9cfc70.png)

**Comment by hanakin** [comment]
none of the components are fixed certain components are contianed in fixed containers while others are not it depends on the component and use. The main area will have more added latter...This is just a test mockup of the components we have coded up so far.
