### ISSUE TITLE
Editor/Quick Editor Component

### ISSUE THREAD

**Issue by hanakin** [phpbb/chameleon#40]
We need the editor component it should work the same for full and quick. The only difference should be preview and title. Look to gmail compose for insights on component layout and design

Codepen: https://codepen.io/hanakin/pen/QPeoWd?editors=1100

**Comment by meis2m** [comment]
that is awesome i see that. i never see this before in any where !
one your advantage works is that it we can see new component that never seen before in any similar platform !

**Comment by hanakin** [comment]
well its essentially the gmail compose so inspiration comes from somewhere...Still need to workout how the topic icons and topic options will fit in...
